// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL7Yl0CaBWcgxq88jW-ia8TvzkzjtNwDg',
    appId: '1:127884660460:web:427e493dd7aa9a7fb7dfc9',
    messagingSenderId: '127884660460',
    projectId: 'trackerapp-d6fc6',
    authDomain: 'trackerapp-d6fc6.firebaseapp.com',
    storageBucket: 'trackerapp-d6fc6.firebasestorage.app',
    measurementId: 'G-ZWNW4FJJCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6XvzOdel6vkRtdSI6pxEBcrCfxehZlik',
    appId: '1:127884660460:android:e58b9781d318234eb7dfc9',
    messagingSenderId: '127884660460',
    projectId: 'trackerapp-d6fc6',
    storageBucket: 'trackerapp-d6fc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxjOzCY-zp59oc6i9Bs7zVGWTjDxXvCGI',
    appId: '1:127884660460:ios:500b71a2d0e8431fb7dfc9',
    messagingSenderId: '127884660460',
    projectId: 'trackerapp-d6fc6',
    storageBucket: 'trackerapp-d6fc6.firebasestorage.app',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxjOzCY-zp59oc6i9Bs7zVGWTjDxXvCGI',
    appId: '1:127884660460:ios:500b71a2d0e8431fb7dfc9',
    messagingSenderId: '127884660460',
    projectId: 'trackerapp-d6fc6',
    storageBucket: 'trackerapp-d6fc6.firebasestorage.app',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL7Yl0CaBWcgxq88jW-ia8TvzkzjtNwDg',
    appId: '1:127884660460:web:f4fa1d5931e59b7eb7dfc9',
    messagingSenderId: '127884660460',
    projectId: 'trackerapp-d6fc6',
    authDomain: 'trackerapp-d6fc6.firebaseapp.com',
    storageBucket: 'trackerapp-d6fc6.firebasestorage.app',
    measurementId: 'G-GGPNWKSVVJ',
  );
}
